version: "3.4"
services:
  todo-app:
    container_name: todo-app-backend
    build: .
    ports:
      - 3000:3000
  mongodb:
    container_name: todo-app-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - todo-app-data:/data/db
volumes:
  todo-app-data: